### ISSUE TITLE
Upper limit of 20 for cube side length 

### ISSUE THREAD

**Issue by DukMastaaa** [DukMastaaa/cppcube#11]
Over 20 gets too excessive, some people (i.e. @Jake-Moss ) get excited and enter in ridiculous numbers so their ram gets eaten 😉

**Comment by pekapikelet** [comment]
https://github.com/DukMastaaa/cppcube/commit/c11b81f44d845ec42121ebcd030f4ee33cdd911e#diff-313fbc20401c955c6defe4eafd6b0049c30478d5752c647d384b420e4f305e2bR208
