### ISSUE TITLE
Esc key to exit popup without confirmation 

### ISSUE THREAD

**Issue by DukMastaaa** [DukMastaaa/cppcube#12]
Possible implementation: maybe provide a signal to do `::keypad(window->fullWindow, false)`?

**Comment by pekapikelet** [comment]
done, instead of changing keypad status, i added the line which changes esc key timeout duration
https://github.com/DukMastaaa/cppcube/blob/e21061c1501fc9646b6d6f593808c8f52d49fe27/src/main.cpp#L26
