### ISSUE TITLE
Fullwidth block characters for timer face

### ISSUE THREAD

**Issue by DukMastaaa** [DukMastaaa/cppcube#13]
Use fullwidth block characters or colour equivalent for timer face because `#` is hard to read

**Comment by pekapikelet** [comment]
Kinda resolved - I'm now using the `ACS_BLOCK` character, which will display an actual block character on terminals that support it, and just a `#` character for those that don't. So far, I haven't used any terminal that displays this properly. Other ACS characters such as `ACS_CKBOARD` (which looks like ▒) don't look good at all when displayed.
