### ISSUE TITLE
Exceptions make stuff go boom

### ISSUE THREAD

**Issue by DukMastaaa** [DukMastaaa/cppcube#6]
Exceptions thrown when handling input through popups just simply crash the program, and don't restore the terminal to the normal state.

**Comment by pekapikelet** [comment]
New approach - reduce the likelihood of exceptions occurring. Handle user input properly so that exceptions mean that something has really gone wrong, not just some bad user input.

**Comment by pekapikelet** [comment]
Finished polishing a lot of things up - exceptions should now only happen in _exceptional_ cases.
